swagger: '2.0'
info:
  title: commercetools payment microservice
  description: Control API of the Integration of the commercetools platform with a Payment Service Provider API
  version: 1.0.0
host: (projectId).(pspName)-payments.commercetools.io
schemes:
  - https
  - http
basePath: /api/v1/
produces:
  - application/json
paths:
  /commercetools/handle/{resource}/{id}/{version}:
    get:
      summary: |
        Trigger to force handling of a commerceotols payment object.
        Passing the Cart or Order instead of the Payment ID enables a more efficient implementation and is therefore preferable.
      parameters:
        - name: resource
          in: path
          description: The resource type the given ID refers to.
          required: true
          type: string
          enum:
            - "cart"
            - "order"
            - "payment"
        - name: id
          in: path
          description: commercetools id of the Payment that should be handled or the Cart or Order whose referenced payment(s) should be handled.
          required: true
          type: string
        - name: version
          in: path
          description: last known version of the Cart, Order or Payment to be handled. Version allows more efficient implementation and protects against concurrent modification an not-yet-consistent state of the CT platform.
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Found the resource and successfully handled it.
          schema:
            $ref: '#/definitions/PaymentStatus'
        '202':
          description: Found the resource, but the payment API could not immediately complete the necessary actions. Please try again later with the identical request.
          schema:
            $ref: '#/definitions/PaymentStatus'
        '403':
          description: The configuration of the service does not allow this request (e.g. not on optional IP whitelist, optional required authentication not passed).
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: One of a) This service is not responsible for the payment interface mentioned in the given payment resource. This service is responsible for the PAYONE interface only. b) (reserved for future cases)
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Given resource could not be found.
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: The given resource does not have the given version yet (platform not yet consistent) or any more (concurrent modification).
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /FooBar/listen:
    get:
      summary: Receives notification / status calls (e.g. webhooks) from the PSP payment interfaces. Completely custom per payment interface implementation.
      responses:
        default:
          description: PSP specific. Often just a string "OK".
definitions:
  PaymentStatus:
    type: object
    properties:
      statusCode:
        description: The HTTP status code.
        type: integer
        format: int32
      message:
        description: The description text of the Status as defined in this api definition (see responses description).
        type: string
      newCartVersion:
        type: integer
        format: int32
        description: The last known version of the Cart Object passed via the cartId parameter. In some situations this can help the frontend implementation save one API call. Implicitly communicates whether something has changed at all.
      newOrderVersion:
        type: integer
        format: int32
        description: The last known version of the Order Object passed via the orderId parameter. In some situations this can help the frontend implementation save one API call. Implicitly communicates whether something has changed at all.
      newPaymentVersion:
        type: integer
        format: int32
        description: the last known version of the Payment Object passed via the paymentId parameter. If called via orderId and the respective Order references just one Payment, the last version of that payment. Otherwise not set. In some situations this can help the frontend implementation save one API call. Implicitly communicates whether something has changed at all.
  Error:
    # This Error Object has the same structure as the commercetools API Error Objects. This allows a coherent pattern and maybe some re-use. See http://dev.commercetools.com/http-api-errors.html#error-responses
    type: object
    properties:
      statusCode:
        description: The HTTP status code of the overall error situation. Must be equal to the actual HTTP status code sent.
        type: integer
        format: int32
      message:
        description: The description of the first error in the "errors" list.
        type: string
      errors:
        description: The full list of errors that have occurred during processing the API request.
        type: array
        items:
          type: object
          properties:
            code:
              description: a free to choose error code for the specific situation.
              type: string
            message:
              description: a matching free text description of the error.  Please be aware that passing error Information from the backend APIs may leak information.
              type: string
