swagger: '2.0'
info:
  title: commercetools payment microservice
  description: Control API of the Integration of the commercetools platform with a Payment Service Provider API
  version: 1.0.0
host: ($projectId).($pspName)-payments.commercetools.io
schemes:
  - https
  - http
basePath: /api
produces:
  - application/json
paths:
  /commercetools/payments/handle:
    get:
      summary: Trigger to force handling of a commerceotols payment object. Parameters paymentId, cartId and orderId are mutually exclusive.
      parameters:
        - name: cartId
          in: query
          description: commercetools id of the Cart whose payment(s) should be handled. Passing the Cart enables a more efficient implementation and is therefore preferable.
          required: false
          type: string
        - name: orderId
          in: query
          description: commercetools id of the Order whose payment(s) should be handled. Passing the Order enables a more efficient implementation and is therefore preferable.
          required: false
          type: string
        - name: paymentId
          in: query
          description: commercetools id of the payment to be handled. I.e. for standalone payments.
          required: false
          type: string
        - name: version
          in: query
          description: Optinally last known version of the Payment or Order to be handled
          required: false
          type: integer
          format: int32
      tags:
        - Products
      responses:
        '200':
          description: Found the Payment and successfully handled changes
          schema:
            $ref: '#/definitions/PaymentStatus'
        '202':
          description: Found the Payment, but the payment API could not immediately complete the necessary actions. Please try again later with the identical request.
          schema:
            $ref: '#/definitions/PaymentStatus'
        '403':
          description: The configuration of the service does not allow this request (e.g. not on optional IP whitelist, optional required authentication not passed etc.).
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Given Payment could not be found.
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Given Payment does not have the optionally given version any more.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /FooBar/listen:
    get:
      summary: Receives notification / status calls (e.g. webhooks) from the PSP payment interfaces. Completely custom per payment interface implementation.
      responses:
        default:
          description: PSP specific. often just a string "OK".
definitions:
  PaymentStatus:
    type: object
    properties:
      status:
        type: string
        description: minimal status description text. The value must not leak any data, it's rather a representation of the HTTP status code.
      newCartVersion:
        type: integer
        format: int32
        description: the last known version of the Cart Object passed via the cartId parameter. In some situations this can help the frontend implementation save one API call. Implicitly communicates, if something has changed at all.
      newOrderVersion:
        type: integer
        format: int32
        description: the last known version of the Order Object passed via the orderId parameter. In some situations this can help the frontend implementation save one API call. Implicitly communicates, if something has changed at all.
      newPaymentVersion:
        type: integer
        format: int32
        description: the last known version of the Payment Object passed via the paymentId parameter. If called via orderId and the respective Order references just one Payment, the last version of that payment. Otherwise not set. In some situations this can help the frontend implementation save one API call. Implicitly communicates, if something has changed at all.
  # This Error Object has the same structure as the commercetools API Error Objects. This allows a coherent pattern and maybe some re-use.
  Error:
    type: object
    properties:
      statusCode:
        type: integer
        format: int32
      message:
        type: string
      errors:
        type: array
        items:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
